### ISSUE TITLE
main language of this document

### ISSUE THREAD

**Issue by thuvh** [undertheseanlp/slp3-vietnamese#3]
https://github.com/undertheseanlp/slp3-vietnamese/blob/91da209588a113f29fbb48224d977709c30a9bd6/util/begin.tex#L3

According to [section *Internationalization* of Latex Documentation](https://en.wikibooks.org/wiki/LaTeX/Internationalization), it should be

```latex
\usepackage[english,vietnam]{babel}
```

After editing, the main language of this book will be Vietnamese, then in the header or prefix of heading, there will be "Chương ", instead of "Chapter ".

**Comment by rain1024** [comment]
chuyển 2 cái này để làm gì anh nhỉ?
